### ISSUE TITLE
Race condition: undefined is not an object (evaluating 'this.parameters[t]=n')

### ISSUE THREAD

**Issue by giautm** [ryanvanderpol/expo-analytics#58] opened 2019-11-12 07:12 UTC
I ran into this exception because `promiseGetWebViewUserAgentAsync()` take to long to complete and parameters stills `undefined`. (a.k.a: Race condition.)

It can fixed by init parameters with an empty object, then copy into current parameters alter promise resolved.

<img width="782" alt="Screen Shot 2019-11-12 at 2 08 21 PM" src="https://user-images.githubusercontent.com/12751435/68649857-43bce280-0556-11ea-9122-8f0657d07306.png">

**Comment by murshudov** [comment] 2019-12-09 07:39
Please give a look at [Expo Analytics Google](https://github.com/mediusoft/expo-analytics-google)

**Comment by ryanvanderpol** [comment] 2019-12-09 13:00
@murshudov quit spamming all the issues in here with your rip off copy of our work. You literally copied this library with no attribution.

**Comment by murshudov** [comment] 2019-12-09 14:48
@ryanvanderpol , first of all, thanks for a great solution. Regarding attribution, I will for sure update the description. Actually I wanted to make a PR at the beginning, but I wanted a static API (something similar to Sentry API) and with all of the changes I needed it would mean a total rewrite of this library. That's why I created new library based on your code for personal project.

**Comment by BillyCottrell** [comment] 2019-12-10 10:19
In that case @murshudov you should have made a fork instead of a straight copy, plus you should have credited @ryanvanderpol as this is his project not yours. Even if there is not a single line of this repository that will be kept afterwards you still have to do this since this repository is the base for your personal project.

**Comment by murshudov** [comment] 2019-12-10 13:56
@BillyCottrell, my bad. Previously didn't work with GitHub as SC and honestly, don't know what forking means and what are the different types of licenses. I will read about them and update repo accordingly to reflect the work done by @ryanvanderpol  as soon as I will have free time.

**Comment by delanebob** [comment] 2020-01-16 17:18
@ryanvanderpol @giautm just wondering if there is any update when https://github.com/ryanvanderpol/expo-analytics/pull/59 will be getting merged in to fix this issue?

Seem to have the same issue myself when I try to call `analytics.addParameter('ul', language);` and it's throwing the same error.

**Comment by ryanvanderpol** [comment] 2020-01-16 17:29
hey @delanebob, have you tried pulling in the branch from #59 and seeing if it resolves your issue?  I'm not able to reproduce the problem myself, so that PR is really just waiting on objective confirmation that it fixes the issue (and does not cause additional side effects).  If you believe #59 resolves the problem here, please drop a comment on it stating so and I'll get it merged and published.

**Comment by delanebob** [comment] 2020-01-17 08:39
Hey @ryanvanderpol, I've just pulled in the branch from #59 now and there doesn't look like there is any side effects. It has also fixed the problem I was getting with the race condition.

I've attached a debug below and it seems like everything is normal.
<img width="1329" alt="Screenshot 2020-01-17 at 08 26 13" src="https://user-images.githubusercontent.com/5358403/72596965-b191db80-3904-11ea-8ad4-d6888bb0af79.png">

Is there anything else in particular you'd like me to double check?

**Closed** 2020-01-24 18:29 UTC
